// Generated by CoffeeScript 1.3.3
(function() {
  var calendar;

  calendar = new Calendar;

  calendar.setViewDate(new Date());

  $("a[href=#hour_view]").click(function() {
    $('.navbar .active').removeClass('active');
    $(this).parent().addClass('active');
    if (!$('#timezone_table table').length) {
      calendar.drawZones();
    }
    $('#calendar').hide();
    $('#timezone_table').show();
    return false;
  });

  $("a[href=#week_view]").click(function() {
    $('.navbar .active').removeClass('active');
    $(this).parent().addClass('active');
    if (!$('#calendar div.header').length) {
      calendar.drawWeeks();
    }
    $('#calendar').show();
    $('#timezone_table').hide();
    return false;
  });

  $("a[href=#week_view]").trigger("click");

}).call(this);
