// Generated by CoffeeScript 1.3.3
(function() {

  $('.date input').datepicker();

  $('form.request .date li a').on('click', function(evt) {
    return $(this).parents('.btn-group').find('button .current').html(this.innerHTML);
  });

  $('form.request .type .btn').on('click', function(evt) {
    return $(this).parents('.type').find('.btn').removeClass('btn-warning btn-success btn-info');
  });

}).call(this);
